export const propDict = {
	name: 'Название',
	latinName: 'Латинское название',
	discoverer: 'Первооткрыватель',
	year: 'Год открытия',
	CASnumber: 'Номер CAS',
	mass: 'Атомный вес. а.е.м. (г*моль-1)',
	radius: 'Радиус атома, пм',
	covradius: 'Ковалентный радиус, пм',
	VDWradius: 'Радиус Ван-дер-Ваальса, пм',
	density: 'Плотность, кг*м-3',
	liquidDensity: 'Плотность жидкости, кг*м-3',
	mohsHardness: 'Твёрдость по Моосу',
	bulkModulus: 'Объёмный модуль упругости, Гпа',
	shearModulus: 'Модуль сдвига, ГПа',
	youngModulusElasticity: 'Модуль упругости Юнга, Гпа',
	oxidationStates: 'Степени окисления',
	boiling: 'Температура кипения, С',
	melting: 'Температура плавления, С',
	molarHeatFusion: 'Молярная теплота плавления, кДж*моль-1',
	specificHeat: 'Удельная теплоёмкость, Дж*кг-1*К-1',
	thermalExpansionCoefficient: 'Коэффициент теплового расширения, К-1',
	molarHeatVaporization: 'Молярная теплота испарения, кДж*моль-1',
	molarVolume: 'Молярный объем, м3*моль-1',
	refractiveIndex: 'Показатель преломления',
	soundSpeed: 'Скорость звука, м*с-1',
	coefficientThermalConductivity: 'Коэффициент теплопроводности, Вт*м-1*К-1',
	electricType: 'Электрический тип',
	specificElectricalConductivity: 'Удельная электропроводность, См*м-1',
	magneticType: 'Магнитный тип',
	bulkMagneticSusceptibility: 'Объёмная магнитная восприимчивость',
	specificMagneticSusceptibility: 'Удельная магнитная восприимчивость, м3*кг-1',
	molarMagneticSusceptibility: 'Молярная магнитная восприимчивость, м3*моль-1',
	resistivity: 'Удельное сопротивление, Ом*м',
	electronegativity: 'Электроотрицательность',
	valence: 'Валентность',
	energyAffinityAtomElectron: 'Энергия сродства атома к электрону, кДж*моль-1',
	firstIonizationEnergy: 'Первая энергия ионизации, кДж*моль-1',
	ionCharge: 'Заряд иона',
	radioactive: 'Радиоактивный',
	halfLife: 'Период полураспада',
	lifetime: 'Время жизни, с',
	nuclearEffectiveCrossSection: 'Ядерное эффективное сечение, барн',
	decayType: 'Тип распада',
	symbol: 'Символ',
	family: 'Семейство',
	number: 'Номер',
	group: 'Группа',
	period: 'Период',
	block: 'Блок',
	state: 'Состояние вещества',
	colour: 'Цвет',
	numberAtomsGasMolecule: 'Количество атомов в молекуле газа'
}