const {Schema, model} = require('mongoose')

const schema = Schema({
	name: {type: String, required: true, unique: true},
	symbol: {type: String, required: true, unique: true},
	family: {type: String},
	number: {type: Number, required: true, unique: true},
	group: {type: Number},
	period: {type: Number},
	block: {type: String},
	latinName: {type: String, required: true, unique: true},
	year: {type: String},
	discoverer: {type: String},
	mass: {type: Number},
	oxidationStates: {type: String},
	radius: {type: Number},
	covradius: {type: Number},
	VDWradius: {type: Number},
	boiling: {type: Number},
	melting: {type: Number},
	state: {type: String},
	molarHeatFusion: {type: Number},
	specificHeat: {type: Number},
	thermalExpansionCoefficient: {type: String},
	molarHeatVaporization: {type: Number},
	colour: {type: String},
	bulkModulus: {type: Number},
	density: {type: Number},
	liquidDensity: {type: Number},
	mohsHardness: {type: Number},
	molarVolume: {type: String},
	shearModulus: {type: Number},
	refractiveIndex: {type: Number},
	soundSpeed: {type: Number},
	coefficientThermalConductivity: {type: Number},
	youngModulusElasticity: {type: Number},
	electricType: {type: String},
	magneticType: {type: String},
	bulkMagneticSusceptibility: {type: String},
	specificMagneticSusceptibility: {type: String},
	molarMagneticSusceptibility: {type: String},
	resistivity: {type: String},
	electronegativity: {type: Number},
	valence: {type: Number},
	energyAffinityAtomElectron: {type: Number},
	firstIonizationEnergy: {type: Number},
	radioactive: {type: String},
	halfLife: {type: String},
	lifetime: {type: String},
	nuclearEffectiveCrossSection: {type: String},
	ionCharge: {type: String},
	numberAtomsGasMolecule: {type: Number},
	CASnumber: {type: String},
	specificElectricalConductivity: {type: String},
	decayType: {type: String}
})

module.exports = model('Element', schema)